#!/usr/bin/env bash
# SNR8503M GCC firmware build script
# Phase 9.2: supports PROFILE= to regenerate include/feature_config.h.
#
# Usage:
#   ./build.sh build                                 # use current feature_config.h
#   ./build.sh build PROFILE=hall_minimal            # regenerate + build
#   ./build.sh build PROFILE=unified_full            # regenerate + build everything
#   ./build.sh clean
#
# Profiles registered (see hall-and-hall-less-plan.json "profiles"):
#   hall_minimal              hall + simple protocol (smallest)
#   hall_bipropellant         hall + bipropellant binary + standard/SNR/position codes
#   hall_bipropellant_full    hall + binary+ASCII + all codes + flash (Phase 8 baseline)
#   sensorless_minimal        sensorless + simple
#   sensorless_bipropellant   sensorless + binary + std/SNR codes
#   unified_minimal           both motors + simple
#   unified_full              everything (may exceed 32 KB MDK-Lite cap)

set -euo pipefail

# ---------------------------------------------------------------------------
# Toolchain (FIX-014: portable selection)
#   1. Honor $ARM_TOOLCHAIN env var (e.g. /opt/gcc-arm-none-eabi-14/bin)
#   2. Try arm-none-eabi-gcc in PATH
#   3. Fall back to PlatformIO's bundled toolchain (Dell's Windows path)
# ---------------------------------------------------------------------------
if [ -n "${ARM_TOOLCHAIN:-}" ] && \
   { [ -x "${ARM_TOOLCHAIN}/arm-none-eabi-gcc" ] || [ -x "${ARM_TOOLCHAIN}/arm-none-eabi-gcc.exe" ]; }; then
    # FIX2-008: also accept .exe extension for Windows MSYS environments
    TOOLCHAIN_BIN="$ARM_TOOLCHAIN"
elif command -v arm-none-eabi-gcc >/dev/null 2>&1; then
    TOOLCHAIN_BIN=$(dirname "$(command -v arm-none-eabi-gcc)")
elif [ -x "/c/Users/Dell/.platformio/packages/toolchain-gccarmnoneeabi/bin/arm-none-eabi-gcc" ]; then
    TOOLCHAIN_BIN="/c/Users/Dell/.platformio/packages/toolchain-gccarmnoneeabi/bin"
else
    echo "ERROR: arm-none-eabi-gcc not found." >&2
    echo "  Set ARM_TOOLCHAIN to your toolchain bin/ dir, or add gcc to PATH." >&2
    exit 2
fi
CC="$TOOLCHAIN_BIN/arm-none-eabi-gcc"
OBJCOPY="$TOOLCHAIN_BIN/arm-none-eabi-objcopy"
SIZE="$TOOLCHAIN_BIN/arm-none-eabi-size"

# ---------------------------------------------------------------------------
# Profile handling — write include/feature_config.h from a named preset
# ---------------------------------------------------------------------------
write_feature_config() {
    local profile="$1"
    local mh mss psim pbin pasc cstd csnr cpos cmot cposc fcfg comment

    case "$profile" in
        hall_minimal)              mh=1; mss=0; psim=1; pbin=0; pasc=0; cstd=0; csnr=0; cpos=0; cmot=0; cposc=0; fcfg=0
                                   comment="Hall + simple protocol (smallest)" ;;
        hall_bipropellant)         mh=1; mss=0; psim=0; pbin=1; pasc=0; cstd=1; csnr=1; cpos=1; cmot=0; cposc=0; fcfg=0
                                   comment="Hall + bipropellant binary + std/SNR/position codes" ;;
        hall_bipropellant_full)    mh=1; mss=0; psim=0; pbin=1; pasc=1; cstd=1; csnr=1; cpos=1; cmot=1; cposc=1; fcfg=1
                                   comment="Hall + binary+ASCII + all codes + flash (Phase 8 baseline)" ;;
        sensorless_minimal)        mh=0; mss=1; psim=1; pbin=0; pasc=0; cstd=0; csnr=0; cpos=0; cmot=0; cposc=0; fcfg=0
                                   comment="Sensorless + simple protocol" ;;
        sensorless_bipropellant)   mh=0; mss=1; psim=0; pbin=1; pasc=0; cstd=1; csnr=1; cpos=0; cmot=0; cposc=0; fcfg=0
                                   comment="Sensorless + bipropellant binary + std/SNR codes" ;;
        unified_minimal)           mh=1; mss=1; psim=1; pbin=0; pasc=0; cstd=0; csnr=0; cpos=0; cmot=0; cposc=0; fcfg=0
                                   comment="Hall + Sensorless auto-detect + simple protocol" ;;
        unified_full)              mh=1; mss=1; psim=0; pbin=1; pasc=1; cstd=1; csnr=1; cpos=1; cmot=1; cposc=1; fcfg=1
                                   comment="Everything — may exceed 32 KB MDK-Lite cap; fine on GCC" ;;
        *)  echo "[ERROR] Unknown profile: $profile" >&2; exit 2 ;;
    esac

    cat > include/feature_config.h <<EOF
/* AUTO-GENERATED by build.sh PROFILE=$profile — do not edit manually.
 * $comment */
#ifndef FEATURE_CONFIG_H
#define FEATURE_CONFIG_H

#define MODULE_MOTOR_HALL                  $mh
#define MODULE_MOTOR_SENSORLESS            $mss
#define MODULE_MOTOR_SENSORLESS_HFI        0   /* keep disabled; STM32-flavoured dead code */

#define MODULE_PROTOCOL_SIMPLE             $psim
#define MODULE_PROTOCOL_BIPROPELLANT_BIN   $pbin
#define MODULE_PROTOCOL_BIPROPELLANT_ASCII $pasc

#define MODULE_CODES_STANDARD              $cstd
#define MODULE_CODES_SNR                   $csnr
#define MODULE_CODES_POSITION              $cpos
#define MODULE_CODES_MOTION                $cmot
#define MODULE_CODES_POSCTRL               $cposc

#define MODULE_FLASH_CONFIG                $fcfg

#if !MODULE_MOTOR_HALL && !MODULE_MOTOR_SENSORLESS
#error "at least one of MODULE_MOTOR_HALL or MODULE_MOTOR_SENSORLESS must be enabled"
#endif
#if MODULE_PROTOCOL_SIMPLE && (MODULE_PROTOCOL_BIPROPELLANT_BIN || MODULE_PROTOCOL_BIPROPELLANT_ASCII)
#error "MODULE_PROTOCOL_SIMPLE cannot coexist with MODULE_PROTOCOL_BIPROPELLANT_*"
#endif
#if MODULE_PROTOCOL_BIPROPELLANT_ASCII && !MODULE_PROTOCOL_BIPROPELLANT_BIN
#error "MODULE_PROTOCOL_BIPROPELLANT_ASCII requires MODULE_PROTOCOL_BIPROPELLANT_BIN"
#endif

#if MODULE_PROTOCOL_SIMPLE || MODULE_PROTOCOL_BIPROPELLANT_BIN
#define MODULE_UART_ENABLED 1
#else
#define MODULE_UART_ENABLED 0
#endif

#if MODULE_MOTOR_HALL && MODULE_MOTOR_SENSORLESS
#define MODULE_MOTOR_AUTODETECT 1
#else
#define MODULE_MOTOR_AUTODETECT 0
#endif

#endif
EOF
}

print_profile_summary() {
    local active_modules=""
    local fc="include/feature_config.h"
    grep -E "^#define MODULE_[A-Z_]+ +1\b" "$fc" 2>/dev/null \
        | awk '{print $2}' | sed 's/MODULE_//' | tr '\n' ' '
}

# ---------------------------------------------------------------------------
# Project paths
# ---------------------------------------------------------------------------
TARGET="snr8503m"
BUILD_DIR="build"

# ---------------------------------------------------------------------------
# Flags
# ---------------------------------------------------------------------------
CPU="-mcpu=cortex-m0 -mthumb"
OPT="-Os"
WARN="-Wall -Wno-unused-function -Wno-unused-variable -Wno-pointer-sign -Wno-implicit-function-declaration"
INCLUDES="-Iinclude -Iperiph_driver/include -Ithird_party/bipropellant-protocol"
CFLAGS="$CPU $OPT $WARN $INCLUDES -ffunction-sections -fdata-sections -std=gnu99 -fno-common -fmessage-length=0"
ASFLAGS="$CPU -c"
LDFLAGS="$CPU -T linker.ld -nostartfiles --specs=nano.specs --specs=nosys.specs -Wl,--gc-sections -Wl,--no-warn-mismatch -Wl,-Map=$BUILD_DIR/$TARGET.map"

VENDOR_LIBS=""  # populated after PROFILE regeneration (see below)

# ---------------------------------------------------------------------------
# Action
# ---------------------------------------------------------------------------
action="${1:-all}"

# Optional PROFILE=name argument anywhere on the command line
PROFILE=""
for arg in "$@"; do
    case "$arg" in
        PROFILE=*) PROFILE="${arg#PROFILE=}" ;;
    esac
done
if [ -n "$PROFILE" ]; then
    echo "[profile] regenerating include/feature_config.h from PROFILE=$PROFILE"
    write_feature_config "$PROFILE"
fi

# Populate VENDOR_LIBS based on current feature_config.h (must run AFTER PROFILE regenerate)
VENDOR_LIBS="vendor_libs/snr8503x_nvr.lib"
if [ -f include/feature_config.h ] && grep -q "^#define MODULE_MOTOR_HALL *1\b" include/feature_config.h; then
    VENDOR_LIBS="vendor_libs/SNR_BLDC_HALL_V1p0.lib $VENDOR_LIBS"
fi
if [ -f include/feature_config.h ] && grep -q "^#define MODULE_MOTOR_SENSORLESS *1\b" include/feature_config.h; then
    # FIX-017: explicit existence check before -nt, which silently returns false on missing files
    if [ ! -f vendor_libs/SNR_BLDC_SNLS_V1p0.lib ]; then
        echo "ERROR: sensorless lib missing: vendor_libs/SNR_BLDC_SNLS_V1p0.lib" >&2
        echo "  Required when MODULE_MOTOR_SENSORLESS=1." >&2
        exit 2
    fi
    if [ ! -f vendor_libs/snr_bldc_snls_renamed.lib ] || [ vendor_libs/SNR_BLDC_SNLS_V1p0.lib -nt vendor_libs/snr_bldc_snls_renamed.lib ]; then
        echo "[lib-rename] BLDC_init/BLDC_1/BLDC_BUFF → *_snls in sensorless lib"
        "$TOOLCHAIN_BIN/arm-none-eabi-objcopy" \
            --redefine-sym BLDC_init=BLDC_init_snls \
            --redefine-sym BLDC_1=BLDC_1_snls \
            --redefine-sym BLDC_BUFF=BLDC_BUFF_snls \
            vendor_libs/SNR_BLDC_SNLS_V1p0.lib vendor_libs/snr_bldc_snls_renamed.lib
    fi
    VENDOR_LIBS="$VENDOR_LIBS vendor_libs/snr_bldc_snls_renamed.lib"
fi

# Print enabled modules at top of any build
if [ -f include/feature_config.h ] && [ "$action" != "clean" ]; then
    enabled=$(grep -E "^#define MODULE_[A-Z_]+ +1\b" include/feature_config.h \
              | awk '{print $2}' | sed 's/MODULE_//' | tr '\n' ' ')
    echo "[modules] $enabled"
fi

clean() {
    rm -rf "$BUILD_DIR"
    echo "[clean] done"
}

build() {
    mkdir -p "$BUILD_DIR/src" "$BUILD_DIR/periph_driver/source" "$BUILD_DIR/third_party/bipropellant-protocol" "$BUILD_DIR/startup"

    local objs=()
    local fail=0

    # Compile C sources
    for src in src/*.c periph_driver/source/*.c third_party/bipropellant-protocol/*.c; do
        [ -f "$src" ] || continue
        obj="$BUILD_DIR/${src%.c}.o"
        mkdir -p "$(dirname "$obj")"
        if ! "$CC" $CFLAGS -c "$src" -o "$obj" 2>&1; then
            echo "[FAIL] compile $src" >&2
            fail=1
        fi
        objs+=("$obj")
    done

    # Assemble startup
    if ! "$CC" $ASFLAGS startup/startup_snr8503x_gnu.S -o "$BUILD_DIR/startup/startup_snr8503x_gnu.o" 2>&1; then
        echo "[FAIL] assemble startup" >&2
        fail=1
    fi
    objs+=("$BUILD_DIR/startup/startup_snr8503x_gnu.o")

    if [ $fail -ne 0 ]; then
        echo "Build aborted due to compile failures." >&2
        exit 1
    fi

    # Link
    echo "[link] $TARGET.elf ..."
    "$CC" $LDFLAGS -o "$BUILD_DIR/$TARGET.elf" "${objs[@]}" $VENDOR_LIBS -lm 2>&1 | tee "$BUILD_DIR/link.log"
    local link_rc=${PIPESTATUS[0]}
    if [ $link_rc -ne 0 ]; then
        echo "[FAIL] link (exit $link_rc) — see $BUILD_DIR/link.log" >&2
        exit $link_rc
    fi

    # Convert
    "$OBJCOPY" -O ihex "$BUILD_DIR/$TARGET.elf" "$BUILD_DIR/$TARGET.hex"
    "$OBJCOPY" -O binary "$BUILD_DIR/$TARGET.elf" "$BUILD_DIR/$TARGET.bin"

    echo "[size]"
    "$SIZE" "$BUILD_DIR/$TARGET.elf"
}

case "$action" in
    all|build) build ;;
    clean) clean ;;
    rebuild) clean; build ;;
    size) "$SIZE" "$BUILD_DIR/$TARGET.elf" ;;
    *) echo "usage: $0 {all|clean|rebuild|size}"; exit 1 ;;
esac
